### ISSUE TITLE
Проблема с inodes

### ISSUE THREAD

**Issue by ZigFisher** [carbonsoft/reductor_satellite_installer#20]
Добрый день !

Скрипты сателлита, работающие в системе, захламляют каталог TMPDIR=/tmp/filter_check/
создавая там кучу мелких файлов.

Основная проблема в том, что если система работает 5+ месяцев, то в этом каталоге будет миллионов 10-15 файлов, которые занимают и соответствующее количество inodes.

Мало того, что система будет тупить и сигнализировать, что inodes заканчиваются, так и еще когда проблема всплывёт наружу, то и удалить их будет проблематично.

Удаление 14,5 миллионов файлов заняло 23 часа.

Пожалуйста, обратите внимание на это !

**Comment by ZigFisher** [comment]
root@clipeus:~# df -i
Filesystem        Inodes    IUsed     IFree IUse% Mounted on
/dev/sda1      121053184 14729879 106323305   13% /
udev             4111438      339   4111099    1% /dev
tmpfs            4113743      578   4113165    1% /run
tmpfs            4113743       16   4113727    1% /dev/shm
tmpfs            4113743       15   4113728    1% /run/lock
tmpfs            4113743       13   4113730    1% /sys/fs/cgroup

**Comment by strizhechenko** [comment]
Исправлено.
